import { FC, ReactNode } from 'react';
import '../styles/globals.css';
import Head from 'next/head'
import type { AppProps } from 'next/app';

const Noop : FC<{children: ReactNode}> = ({ children }) => <>{children}</>

function App({ Component, pageProps }: AppProps) {
  //TODO: 型定義なんとかする
  const Layout = (Component as any).Layout || Noop;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Component {...pageProps} />
      </Layout>
    </>
  );
}

export default App;
